# Generated by Django 3.2.3 on 2021-06-09 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(editable=False, max_length=40)),
                ('start_time', models.DateTimeField(editable=False)),
                ('end_time', models.DateTimeField(editable=False)),
                ('session', models.BooleanField(default=False, editable=False)),
                ('completed', models.BooleanField(default=False, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Ongoing', 'Ongoing'), ('Future', 'Future')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('type', models.CharField(choices=[('MCQ', 'MCQ'), ('Subjective', 'Subjective')], max_length=20)),
                ('total', models.IntegerField(default=1)),
                ('current_no', models.IntegerField(default=None, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseApp.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(editable=False)),
                ('type', models.CharField(choices=[('MCQ', 'MCQ'), ('Subjective', 'Subjective')], editable=False, max_length=20)),
                ('total', models.IntegerField(editable=False)),
                ('current_no', models.IntegerField(default=None, editable=False)),
                ('quiz', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='BaseApp.completedquiz')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedChoiceSubjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to='documents/')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseApp.question')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedChoiceMCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(editable=False, max_length=100)),
                ('select', models.BooleanField(default=False, editable=False)),
                ('correct', models.BooleanField(default=False, editable=False)),
                ('question', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='BaseApp.completedquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceSubjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to='documents/')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseApp.question')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceMCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('select', models.BooleanField(default=False)),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseApp.question')),
            ],
        ),
    ]
